import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  aiSidebar:[
    "AI360/Overview",
  ],
  azureSidebar: [
    "Azure360/Introduction",
    {
      type: "category",
      label: "Azure Fundamentals",
      link: {
        type: "generated-index",
        title: "Azure Fundamentals",
        description:
          "This section gives an overview of the core components in Azure cloud environment. Feel free to skip this section if you are already familiar with Azure. ",
        keywords: ["Azure360"],
      },
      items: [
        "Azure360/Azure Fundamentals/Cloud Computing",
        "Azure360/Azure Fundamentals/Different Cloud Models",
        {
          type: "category",
          label: "Cloud Service Types",
          link: {
            type: "generated-index",
            title: "Cloud Service Types",
            description: `
            Cloud service types are divided into three:\n
            IaaS - Infrastructure as a Service,\n
            PaaS - Platform as a Service,\n
            SaaS - Software as a Service`,
            keywords: ["Azure360"],
          },
          items: [
            "Azure360/Azure Fundamentals/Cloud Service Types/Infrastructure as a Service",
            "Azure360/Azure Fundamentals/Cloud Service Types/Platform as a Service",
            "Azure360/Azure Fundamentals/Cloud Service Types/Software as a Service",
          ],
        },
        "Azure360/Azure Fundamentals/Cloud Services Cost Model",
        "Azure360/Azure Fundamentals/Benefits of using Cloud Services",
        {
          type: "category",
          label: "Architectural Components",
          link: {
            type: "generated-index",
            title: "Architectural Components",
            description:
              "The architectural component of Azure includes the physical infrastructure of Azure (datacenters, availability zones and regions) and the management infrastructure of Azure (resources, resource groups, subscriptions and management groups)",
            keywords: ["Azure360"],
          },
          items: [
            "Azure360/Azure Fundamentals/Azure Architectural Components/Physical Infrastructure",
            "Azure360/Azure Fundamentals/Azure Architectural Components/Management Infrastructure",
          ],
        },
        "Azure360/Azure Fundamentals/Additional Resources",
      ],
    },
    {
      type: "category",
      label: "Azure Best Practices",
      link: {
        type: "generated-index",
        title: "Azure Best Practices",
        description: "Learn about the Azure best practices!",
        keywords: ["Azure360"],
      },
      items: [
        "Azure360/Azure Best Practices/Prerequisite",
        "Azure360/Azure Best Practices/Physical Infrastructure",
        "Azure360/Azure Best Practices/Management Infrastructure",
        "Azure360/Azure Best Practices/Naming Convention",
        {
          type: "category",
          label: "Azure Security",
          link: {
            type: "generated-index",
            title: "Azure Security",
            description:
              "Implementing security best practices in Azure is crucial to protect cloud resources, data and applications from various threats.",
            keywords: ["Azure360"],
          },
          items: [
            "Azure360/Azure Best Practices/Azure Security/Identity Management",
            {
              type: "category",
              label: "Governance",
              link: {
                type: "generated-index",
                title: "Governance",
                description: "Learn about the Governance!",
                keywords: ["Azure360"],
              },
              items: [
                "Azure360/Azure Best Practices/Azure Security/Governance/Overview",
                {
                  type: "category",
                  label: "Implementation",
                  link: {
                    type: "generated-index",
                    title: "Implementation",
                    description:
                      "Learn about the ways to Implement Governance in Azure!\nGovernance can be applied by leveraging tools like Azure Policy, Blueprints, Tags, RBAC, Management Groups, Cost management & Monitoring.",
                    keywords: ["Azure360"],
                  },
                  items: [
                    "Azure360/Azure Best Practices/Azure Security/Governance/Implementation/Azure Policy",
                    "Azure360/Azure Best Practices/Azure Security/Governance/Implementation/Azure Blueprint",
                    "Azure360/Azure Best Practices/Azure Security/Governance/Implementation/Azure Tags",
                    "Azure360/Azure Best Practices/Azure Security/Governance/Implementation/Azure Management Groups",
                    "Azure360/Azure Best Practices/Azure Security/Governance/Implementation/Azure RBAC",
                    "Azure360/Azure Best Practices/Azure Security/Governance/Implementation/Azure Monitoring",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Networking",
              link: {
                type: "generated-index",
                title: "Networking",
                description:
                  "Networking in Azure refers to the suite of services, tools and infrastructure that enable connectivity and communication between various resources and services within the Azure cloud environment, as well as between Azure and on-premises or other cloud environments !",
                keywords: ["Azure360"],
              },
              items: [
                "Azure360/Azure Best Practices/Azure Security/Networking/Virtual Network",
                {
                  type: "category",
                  label: "Security Groups",
                  link: {
                    type: "generated-index",
                    title: "Security Groups",
                    description: "Learn about the Azure Security Groups!",
                    keywords: ["Azure360"],
                  },

                  items: [
                    "Azure360/Azure Best Practices/Azure Security/Networking/Security Groups/Network Security Groups",
                    "Azure360/Azure Best Practices/Azure Security/Networking/Security Groups/Application Security Group",
                  ],
                },
                "Azure360/Azure Best Practices/Azure Security/Networking/VNet DDos",
                {
                  type: "category",
                  label: "VNet Endpoints",
                  link: {
                    type: "generated-index",
                    title: "VNet Endpoints",
                    description: "Learn about the VNet Endpoints!",
                    keywords: ["Azure360"],
                  },
                  items: [
                    "Azure360/Azure Best Practices/Azure Security/Networking/Endpoints/Private Endpoints",
                    "Azure360/Azure Best Practices/Azure Security/Networking/Endpoints/Service Endpoints",
                    "Azure360/Azure Best Practices/Azure Security/Networking/Endpoints/Comparison",
                  ],
                },
                "Azure360/Azure Best Practices/Azure Security/Networking/VNet Peering",
              ],
            },
            "Azure360/Azure Best Practices/Azure Security/Secrets Management",
            "Azure360/Azure Best Practices/Azure Security/VPN Gateway & Express Route",
            "Azure360/Azure Best Practices/Azure Security/Azure Firewall & Application Gateway",
          ],
        },
        {
          type: "category",
          label: "Application Services",
          link: {
            type: "generated-index",
            title: "Application Services",
            description:
              "Learn More about Azure Application Services!",
            keywords: ["Azure360"],
          },
          items: [
            "Azure360/Azure Best Practices/Application Services/App Service",
            "Azure360/Azure Best Practices/Application Services/Storage Account",
            "Azure360/Azure Best Practices/Application Services/Container Registry",
            "Azure360/Azure Best Practices/Application Services/Virtual Machine",
            "Azure360/Azure Best Practices/Application Services/Application Gateway",
          ],
        },
        "Azure360/Azure Best Practices/Open AI Services",
        "Azure360/Azure Best Practices/Deployment Automation",
        "Azure360/Azure Best Practices/Cost Management",
        "Azure360/Azure Best Practices/Monitoring",
        "Azure360/Azure Best Practices/Disaster Recovery",
        "Azure360/Azure Best Practices/Project Checklist",
        "Azure360/Azure Best Practices/Project Design Document",
        {
          type: "category",
          label: "Debug Tools",
          link: {
            type: "generated-index",
            title: "Azure Debug Tools",
            description:
              "Learn More about Azure Debug Tools!",
            keywords: ["Azure360"],
          },
          items: [
            "Azure360/Azure Best Practices/Debug Tools/Azure Network Watcher",
            {
              type: "category",
              label: "IP Address Tools",
              link: {
                type: "generated-index",
                title: "IP Address Tools",
                description:
                  "Learn More about IP Address Tools!",
                keywords: ["Azure360"],
              },
              items: [
                "Azure360/Azure Best Practices/Debug Tools/IP Address Tools/IPv4",
                "Azure360/Azure Best Practices/Debug Tools/IP Address Tools/IPv6",
                "Azure360/Azure Best Practices/Debug Tools/IP Address Tools/More Tools",
              ]
            },
            "Azure360/Azure Best Practices/Debug Tools/DNS Lookup & Records",
            "Azure360/Azure Best Practices/Debug Tools/cURL",
          ]
        },
      ],
    },
  ],
  ragSidebar: [
    "RAG360/Introduction",
    "RAG360/Fundamentals of RAG",
    {
      type: "category",
      label: "Types of RAG",
      link: {
        type: "generated-index",
        title: "Types of RAG",
        description:
          "Learn more about Types of RAG360 ",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Types of RAG/Overview",
        "RAG360/Types of RAG/Naive RAG",
        "RAG360/Types of RAG/Advanced RAG",
        "RAG360/Types of RAG/Modular RAG",
        "RAG360/Types of RAG/Graph RAG",
      ],
    },
    {
      type: "category",
      label: "Data Ingestion",
      link: {
        type: "generated-index",
        title: "Data Ingestion",
        description: "Learn more about Data Ingestion",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Data Ingestion/Overview",
        {
          type: "category",
          label: "Data Preparation",
          link: {
            type: "generated-index",
            title: "Data Preparation",
            description: "Learn more about Data Preparation",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Data Ingestion/Data Preparation/Overview",
            {
              type: "category",
              label: "Source Connectors",
              link: {
                type: "generated-index",
                title: "Source Connectors",
                description: "Learn more about Source Connectors",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Data Ingestion/Data Preparation/Source Connectors/Overview",
                "RAG360/Data Ingestion/Data Preparation/Source Connectors/Share Point Reader",
                "RAG360/Data Ingestion/Data Preparation/Source Connectors/Local Directory Reader",
                "RAG360/Data Ingestion/Data Preparation/Source Connectors/Confluence Reader"
              ]
            },
            {
              type: "category",
              label: "Source Documents",
              link: {
                type: "generated-index",
                title: "Source Documents",
                description: "Learn more about Source Documents",
                keywords: ["RAG360"],
              },
              items: [
                {
                  type: "category",
                  label: "PDF",
                  link: {
                    type: "generated-index",
                    title: "PDF",
                    description: "Learn more about PDF",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Data Ingestion/Data Preparation/Source Documents/PDF/Manual Document Preparation",
                    "RAG360/Data Ingestion/Data Preparation/Source Documents/PDF/Power Automate",
                    "RAG360/Data Ingestion/Data Preparation/Source Documents/PDF/Unstructured.io",
                    "RAG360/Data Ingestion/Data Preparation/Source Documents/PDF/LayoutPDF Parser",
                  ]
                },
                "RAG360/Data Ingestion/Data Preparation/Source Documents/Doc",
                "RAG360/Data Ingestion/Data Preparation/Source Documents/Register Map",
                "RAG360/Data Ingestion/Data Preparation/Source Documents/Instrument Drivers",
                "RAG360/Data Ingestion/Data Preparation/Source Documents/Specification Document",
              ]
            },
          ]
        },
        {
          type: "category",
          label: "Chunking",
          link: {
            type: "generated-index",
            title: "Chunking",
            description: "Learn more about Chunking",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Data Ingestion/Chunking/Overview",
            "RAG360/Data Ingestion/Chunking/Different Chunking Methods",
            "RAG360/Data Ingestion/Chunking/Page by Page Chunking",
            "RAG360/Data Ingestion/Chunking/Recursive character text spiltter",
            "RAG360/Data Ingestion/Chunking/Meta Data Attachment",
          ]
        },
        {
          type: "category",
          label: "Embedding",
          link: {
            type: "generated-index",
            title: "Embedding",
            description: "Learn more about Embedding",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Data Ingestion/Embedding/Overview",
            {
              type: "category",
              label: "Model",
              link: {
                type: "generated-index",
                title: "Model",
                description: "Learn more about Model",
                keywords: ["RAG360"],
              },
              items: [
                {
                  type: "category",
                  label: "Offline",
                  link: {
                    type: "generated-index",
                    title: "Offline",
                    description: "Learn more about Offline",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Data Ingestion/Embedding/Model/Offline/Jina",
                    "RAG360/Data Ingestion/Embedding/Model/Offline/Nomic",
                  ]
                },
                {
                  type: "category",
                  label: "Online",
                  link: {
                    type: "generated-index",
                    title: "Online",
                    description: "Learn more about Online",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Data Ingestion/Embedding/Model/Online/OpenAI",
                  ]
                },
              ]
            },
            {
              type: "category",
              label: "Sparse Vector",
              link: {
                type: "generated-index",
                title: "Sparse Vector",
                description: "Learn more about Sparse Vector",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Data Ingestion/Embedding/Sparse Vector/Overview",
                "RAG360/Data Ingestion/Embedding/Sparse Vector/BM25",
                "RAG360/Data Ingestion/Embedding/Sparse Vector/TF-TDF",
                "RAG360/Data Ingestion/Embedding/Sparse Vector/Splade",
              ]
            },
            {
              type: "category",
              label: "Dense Vector",
              link: {
                type: "generated-index",
                title: "Dense Vector",
                description: "Learn more about Dense Vector",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Data Ingestion/Embedding/Dense Vector/Overview",
              ]
            }
          ]
        },
        {
          type: "category",
          label: "Vector Database",
          link: {
            type: "generated-index",
            title: "Vector Database",
            description: "Learn more about Vector Database",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Data Ingestion/Vector Database/Overview",
            {
              type: "category",
              label: "Online",
              link: {
                type: "generated-index",
                title: "Online",
                description: "Learn more about Online",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Data Ingestion/Vector Database/Online/Rockset",
                "RAG360/Data Ingestion/Vector Database/Online/Pine Cone",
              ]
            },
            {
              type: "category",
              label: "In-Memory",
              link: {
                type: "generated-index",
                title: "In-Memory",
                description: "Learn more about In-Memory",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Data Ingestion/Vector Database/In-Memory/FAISS",
                "RAG360/Data Ingestion/Vector Database/In-Memory/Chroma-DB",
              ]
            },
            {
              type: "category",
              label: "Self Hosted",
              link: {
                type: "generated-index",
                title: "Self Hosted",
                description: "Learn more about Self Hosted",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Data Ingestion/Vector Database/Self Hosted/Qdrant",
                "RAG360/Data Ingestion/Vector Database/Self Hosted/Weaviate",
                "RAG360/Data Ingestion/Vector Database/Self Hosted/Milvus",
              ]
            },
            "RAG360/Data Ingestion/Vector Database/Comparisons"
          ]
        },
      ]
    },
    {
      type: "category",
      label: "Retrieval",
      link: {
        type: "generated-index",
        title: "Retrieval",
        description: "Learn more about Retrieval",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Retrieval/Overview",
        {
          type: "category",
          label: "UnStructured",
          link: {
            type: "generated-index",
            title: "UnStructured",
            description: "Learn more about UnStructured",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Retrieval/Unstructured/Overview",
            {
              type: "category",
              label: "Query Optimization",
              link: {
                type: "generated-index",
                title: "Query Optimization",
                description: "Learn more about Query Optimization",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Retrieval/Unstructured/Query Optimization/Overview",
                {
                  type: "category",
                  label: "Query Routing",
                  link: {
                    type: "generated-index",
                    title: "Query Routing",
                    description: "Learn more about Query Routing",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Query Optimization/Query Routing/Overview",
                    "RAG360/Retrieval/Unstructured/Query Optimization/Query Routing/Task Based Retrieval",
                  ]
                },
                {
                  type: "category",
                  label: "Query Transformations",
                  link: {
                    type: "generated-index",
                    title: "Query Transformations",
                    description: "Learn more about Query Transformations",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Query Optimization/Query Transformations/Overview",
                    "RAG360/Retrieval/Unstructured/Query Optimization/Query Transformations/Query Expansion",
                    "RAG360/Retrieval/Unstructured/Query Optimization/Query Transformations/Hypothetical Questions",
                  ]
                }
              ]
            },
            {
              type: "category",
              label: "Searching",
              link: {
                type: "generated-index",
                title: "Searching",
                description: "Learn more about Searching",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Retrieval/Unstructured/Searching/Overview",
                {
                  type: "category",
                  label: "Semantic Searching",
                  link: {
                    type: "generated-index",
                    title: "Semantic Searching",
                    description: "Learn more about Semantic Searching",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Searching/Semantic Search/Overview",
                    "RAG360/Retrieval/Unstructured/Searching/Semantic Search/ANN",
                    "RAG360/Retrieval/Unstructured/Searching/Semantic Search/KNN",
                    "RAG360/Retrieval/Unstructured/Searching/Semantic Search/Comparison",
                  ]
                },
                {
                  type: "category",
                  label: "Keyword Searching",
                  link: {
                    type: "generated-index",
                    title: "Keyword Searching",
                    description: "Learn more about Keyword Searching",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Searching/Keyword Search/Overview",
                    "RAG360/Retrieval/Unstructured/Searching/Keyword Search/BM25",
                  ]
                },
                {
                  type: "category",
                  label: "Hybrid Searching",
                  link: {
                    type: "generated-index",
                    title: "Hybrid Searching",
                    description: "Learn more about Hybrid Searching",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Searching/Hybrid Search/Overview",
                    "RAG360/Retrieval/Unstructured/Searching/Hybrid Search/Qdrant",
                    "RAG360/Retrieval/Unstructured/Searching/Hybrid Search/Fusion Retriver",
                  ]
                }
              ]
            },
            "RAG360/Retrieval/Unstructured/Meta-Data Filtering",
            {
              type: "category",
              label: "Re Ranking",
              link: {
                type: "generated-index",
                title: "Re Ranking",
                description: "Learn more about Re Ranking",
                keywords: ["RAG360"],
              },
              items: [
                {
                  type: "category",
                  label: "Model-Based Re Ranking",
                  link: {
                    type: "generated-index",
                    title: "Model-Based Re Ranking",
                    description: "Learn more about Model-Based Re Ranking",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Reranking/Model-Based/Overview",
                    "RAG360/Retrieval/Unstructured/Reranking/Model-Based/Late Interaction",
                    "RAG360/Retrieval/Unstructured/Reranking/Model-Based/Cross Embedding Models",
                    "RAG360/Retrieval/Unstructured/Reranking/Model-Based/Chat LLM",
                    "RAG360/Retrieval/Unstructured/Reranking/Model-Based/LLM Reranker",
                  ]
                },
                {
                  type: "category",
                  label: "Logical Ranking",
                  link: {
                    type: "generated-index",
                    title: "Logical Ranking",
                    description: "Learn more about Logical Ranking",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Retrieval/Unstructured/Reranking/Logical Reranking/Overview",
                    "RAG360/Retrieval/Unstructured/Reranking/Logical Reranking/Relative Score Fusion",
                    "RAG360/Retrieval/Unstructured/Reranking/Logical Reranking/Reciprocal Reranking",
                  ]
                },
              ]
            },
            "RAG360/Retrieval/Unstructured/Contextual Compressors",
            "RAG360/Retrieval/Unstructured/Context Enrichment",
          ]
        },
        {
          type: "category",
          label: "Structured",
          link: {
            type: "generated-index",
            title: "Structured",
            description: "Learn more about Structured",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Retrieval/Structured/Overview",
            "RAG360/Retrieval/Structured/PandasSQL",
            "RAG360/Retrieval/Structured/PandasLLM",
          ]
        },
        "RAG360/Retrieval/Story"        
      ]
    },
    {
      type: "category",
      label: "Generation",
      link: {
        type: "generated-index",
        title: "Generation",
        description: "Learn more about Generation",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Generation/Overview",
        {
          type: "category",
          label: "Types of Generation",
          link: {
            type: "generated-index",
            title: "Types of Generation",
            description: "Learn more about Types of Generation",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Generation/Types of Generation/Summarization",
            "RAG360/Generation/Types of Generation/Inferring",
            "RAG360/Generation/Types of Generation/Transforming",
            "RAG360/Generation/Types of Generation/Expanding",
            "RAG360/Generation/Types of Generation/Chatbot",

          ],
        },
        "RAG360/Generation/Grounding",
        {
          type: "category",
          label: "Prompting Techniques",
          link: {
            type: "generated-index",
            title: "Prompting Technique",
            description: "Learn more about Prompting Technique",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Generation/Prompting Techniques/Overview",
            "RAG360/Generation/Prompting Techniques/Chain of Thoughts",
            "RAG360/Generation/Prompting Techniques/Tree of Thoughts",
          ],
        },
        {
          type: "category",
          label: "Model",
          link: {
            type: "generated-index",
            title: "Model",
            description: "Learn more about Model",
            keywords: ["RAG360"],
          },
          items: [
            {
              type: "category",
              label: "Offline",
              link: {
                type: "generated-index",
                title: "Offline",
                description: "Learn more about Offline",
                keywords: ["RAG360"],
              },
              items: [
                {
                  type: "category",
                  label: "Ollama",
                  link: {
                    type: "generated-index",
                    title: "Ollama",
                    description: "Learn more about Ollama",
                    keywords: ["RAG360"],
                  },
                  items: [
                    "RAG360/Generation/models/Offline/Ollama/Overview",
                    "RAG360/Generation/models/Offline/Ollama/Llama 3",
                    "RAG360/Generation/models/Offline/Ollama/Qwen 2",
                    "RAG360/Generation/models/Offline/Ollama/Mistral Nemo",
                  ],
                },
                "RAG360/Generation/models/Offline/Comparisons"
              ],
            },
            {
              type: "category",
              label: "Online",
              link: {
                type: "generated-index",
                title: "Online",
                description: "Learn more about Online",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Generation/models/Online/Open AI",
                "RAG360/Generation/models/Online/Azure Open AI",
                "RAG360/Generation/models/Online/AWS Bedrock",
                "RAG360/Generation/models/Online/Comparisons",
              ],
            }
          ],
        },
        "RAG360/Generation/Improvements",
        {
          type: "category",
          label: "Security",
          link: {
            type: "generated-index",
            title: "Security",
            description: "Learn more about Security",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Generation/Security/Overview",
            "RAG360/Generation/Security/Guardrails",
          ],
        }
      ]
    },
    {
      type: "category",
      label: "Evaluation",
      link: {
        type: "generated-index",
        title: "Evaluation",
        description: "Learn more about Evaluation",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Evaluation/Overview",
        {
          type: "category",
          label: "Evaluation Framework",
          link: {
            type: "generated-index",
            title: "Evaluation Framework",
            description: "Learn more about Evaluation Framework",
            keywords: ["RAG360"],
          },
          items: [
            {
              type: "category",
              label: "Trulens",
              link: {
                type: "generated-index",
                title: "Trulens",
                description: "Learn more about Trulens",
                keywords: ["RAG360"],
              },
              items: [
                "RAG360/Evaluation/Evaluation Framework/Trulens/Overview",
                "RAG360/Evaluation/Evaluation Framework/Trulens/Key Terminologies",
                "RAG360/Evaluation/Evaluation Framework/Trulens/Modules",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Metrics",
          link: {
            type: "generated-index",
            title: "Metrics",
            description: "Learn more about Metrics",
            keywords: ["RAG360"],
          },
          items: [
            "RAG360/Evaluation/Metrics/Custom Metric",
            "RAG360/Evaluation/Metrics/System Metrics vs Module Metrics",
            "RAG360/Evaluation/Metrics/Good Metrics vs Bad Metrics",
            "RAG360/Evaluation/Metrics/Context Relevance",
            "RAG360/Evaluation/Metrics/Groundedness",
            "RAG360/Evaluation/Metrics/Answer Relevance",
          ],
        }
      ],
    },
    {
      type: "category",
      label: "Tracking",
      link: {
        type: "generated-index",
        title: "Tracking",
        description: "Learn more about Tracking",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Tracking/Overview",
        "RAG360/Tracking/Tracking for Debugging",
        "RAG360/Tracking/Cost Usage",
      ],
    },
    {
      type: "category",
      label: "Challenges in RAG",
      link: {
        type: "generated-index",
        title: "Challenges in RAG",
        description: "Learn more about Challenges in RAG",
        keywords: ["RAG360"],
      },
      items: [
        "RAG360/Challenges in RAG/Challenges",
      ],
    },
    "RAG360/Project Checklist",
  ],
  codingStandardsSidebar:[
    "CodingStandards/Software Engineer Practices",
    {
      type: "category",
      label: "Archictures",
      link: {
        type: "generated-index",
        title: "Archictures",
        description:
          "Learn more about Archictures ",
        keywords: ["c4_model"],
      },
      items: [
        "CodingStandards/Archictures/c4_model",
      ],
    },
    {
      type: "category",
      label: "Books",
      link: {
        type: "generated-index",
        title: "Books",
        description:
          "Learn more about Books ",
        keywords: ["Books"],
      },
      items: [
        "CodingStandards/Books/Clean-code",
        "CodingStandards/Books/PragmaticProgrammer"
      ],
    },
    {
      type: "category",
      label: "Python",
      link: {
        type: "generated-index",
        title: "Books",
        description:
          "Learn more about Python ",
        keywords: ["Python"],
      },
      items: [
        "CodingStandards/Python/DependencyManagement",
        "CodingStandards/Python/PythonCodingStandards"
      ],
    },
    {
      type: "category",
      label: "React",
      link: {
        type: "generated-index",
        title: "React",
        description:
          "Learn more about React ",
        keywords: ["React"],
      },
      items: [
        "CodingStandards/React/React",
      ],
    },
    
  ],
  devOpsSidebar:[    
    {
      type: "category",
      label: "ContinousIntergration",
      link: {
        type: "generated-index",
        title: "ContinousIntergration",
        description:
          "Learn more about Continous Intergration ",
        keywords: ["ContinousIntergration"],
      },
      items: [
        "DevOps/ContinousIntergration/ContinousIntergration",
      ],
    },
    {
      type: "category",
      label: "Docker",
      link: {
        type: "generated-index",
        title: "Docker",
        description:
          "Learn more about Docker",
        keywords: ["Docker"],
      },
      items: [
        "DevOps/Docker/Docker",
      ],
    },
    {
      type: "category",
      label: "TrunkBasedDevelopment",
      link: {
        type: "generated-index",
        title: "TrunkBasedDevelopment",
        description:
          "Learn more about TrunkBasedDevelopment",
        keywords: ["TrunkBasedDevelopment"],
      },
      items: [
        "DevOps/TrunkBasedDevelopment/Overview",
        "DevOps/TrunkBasedDevelopment/ReleaseProcess",
      ],
    },
    {
        type: "category",
        label: "Kubernites",
        link: {
          type: "generated-index",
          title: "Kubernites",
          description:
            "Learn more about Kubernites",
          keywords: ["Kubernites"],
        },
        items: [
          "DevOps/Kubernites/Overview",
        ],
    },
    "DevOps/AcceptanceTable",
    "DevOps/AdoptionProcess",
    "DevOps/DeploymentAutomation",
    "DevOps/GITVersionControl",
    "DevOps/MeasuringSoftwareEngineeringPractics",
    "DevOps/TestAutomation",
    "DevOps/SoftwareEngineeringPractics",    
  ],
  graphsidebar:[
    "KnowledgeBase/KnowledgeBase",
  ]
};

export default sidebars;
